# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 0.0.0.$(rev:r)
trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud Olivier Delmotte'
    organization: 'odelmotte'
    scannerMode: 'MSBuild'
    projectKey: 'hangar18rip.h18.SpecFlow.SeleniumHookChrome'
    projectName: '[h18] SpecFlow.SeleniumHookChrome'
    projectVersion: '$(Build.BuildNumber)'
- script: dotnet restore
  workingDirectory: src/
  displayName: 'dotnet restore'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--no-restore -p:Version=$(Build.BuildNumber) -p:AssemblyVersion=$(Build.BuildNumber) -p:FileVersion=$(Build.BuildNumber) -p:AssemblyInformationalVersionAttribute="GitHub_Commit-$(Build.SourceVersion)'
    workingDirectory: 'src/'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    arguments: '--no-restore --no-build --verbosity normal --collect "Code coverage"'
    testRunTitle: 'Unit Tests'
    workingDirectory: 'src/'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'src/'
    Contents: '**/*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/nuget'
    flattenFolders: true
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/nuget'
    artifact: 'nuget'
    publishLocation: 'pipeline'